version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "customerdb"
      POSTGRES_USER: "customer"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"